.TH BUDGIE-DAEMON "1" "April 2017" "budgie-daemon 10.3" "User Commands"
.SH NAME
budgie-daemon \- Desktop Daemon that is auto-run on logon
.SH DESCRIPTION
.SS "Usage:"
.IP
budgie\-daemon
.SH "SEE ALSO"
The full documentation for
.B budgie-daemon
is maintained as a Texinfo manual.  If the
.B info
and
.B budgie-daemon
programs are properly installed at your site, the command
.IP
.B info budgie-daemon
.PP
should give you access to the complete manual.
